import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import ProfilePic from "@/../public/images/profile/developer-pic-1.png";
import LightBulb from "@/../public/images/svgs/miscellaneous_icons_1.svg";
import AnimatedText from "@/components/AnimatedText";
import { LinkArrow } from "@/components/Icons";
import Link from "next/link";
import TransitionEffect from "@/components/TransitionEffect";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Leon Wei | Main Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="text-2xl flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex  items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={ProfilePic} alt="background"
                className="w-full h-auto lg:hidden md:!inline-block md:w-full"
                priority
                sizes="(max-width:768px) 100vw, (max-width:1200px) 50vw, 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Be Assiduity. Be Brave. Be Curious."
                className="text-left xl:!text-6xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-4xl xs:!text-3xl "
              />
              <p className="my-4 text-base font-medium">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. This site is showcasing my expertise in React.js and
                details of my career history.
              </p>

              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link href="/Resume of Leon Lee En Wei.pdf" target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 
              px-6 rounded-lg text-lg font-semibold
              hover:bg-light hover:text-dark border-2 border-solid 
              border-transparent hover:border-light dark:bg-light dark:text-dark 
              hover:dark:bg-dark hover:dark:text-light hover:dark:border-light"
                  download={true}>Resume <LinkArrow className={"w-6 ml-1"}></LinkArrow>
                </Link>
                <Link href="mailto:leonweiwei5@gmail.com" target="_blank" className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light">Contact</Link>
              </div>
            </div>

          </div>
        </Layout>
        {/*}
        <div className="absolute right-8 bottom-8 inline-block w-24">
          <Image src={LightBulb} alt="miss" className="w-full h-auto" />
  </div>*/}
      </main>
    </>
  );
}
